name: MetadataTP
version: 1.0 Beta
main: me.TigerReborn.MetadataTP.IMetadataTP
commands:
  tprequestaccept:
    aliases: [tpra, tpraccept]
    permission: metadatatp.tpra
  tprequestdeny:
    aliases: [tprdeny, tprd]
    permission: metadatatp.tprd
  tphererequest:
    aliases: [tprh, tprhere]
    permission: metadatatp.tprh
  tprequest:
    aliases: [tpr, tpreq]
    permission: metadatatp.tpr